package com.roommatecomplaint

import org.bson.types.ObjectId

class User {

	transient springSecurityService

	ObjectId id
	String uid //facebook id
	String accessToken
	String name
	Date dateCreated

	/* 
     * Changes to be made and remove the autogenerated setter 
     * which is generated with `grails s2-quickstart com.example User Role` (for example)
     */
    Set<Role> authorities

    /* 
     * Include this in every domain class generated by spring security
     * if you do not include this it will search for hibernate to persist it
     */
    static mapWith = 'mongo'

    static embedded = ['authorities']
    /* 
     * End of changes
     */
    
    static constraints = {
        uid blank: false, unique: true
    }

    static mapping = {
        
    }
}
